### ISSUE TITLE
Games.xml

### ISSUE THREAD

**Issue by FelixV** [GadgetFactory/Arcade-Blaster#1]
1. Pong Demo :: Publisher "Homebrew" typoed as "Homwbrew"
2. Pac-Man (1980) set hashes are actually Puckman (Namco 1979) [mame puckman]
3. Pac-Man (Midway 1980) works [mame pacman]
4. Caterpillar (Pac-Man hack) [mame ctrpllrp] works, with a small gfx issue. not sure if its the pac-core or just me not config xml properly

**Comment by gmpundlik** [comment]
Hi Felix, thanks for pointing this out. Please send the corrected games.xml file (gmpundlik@gadgetfactory.net) to me and I will upload it as fix.

Did you make separate entries for pacman and puckman (and ctrpllrp) or defined another fileset? The idea for <fileset> was to support multiple variations of the game running on same hardware without having to make a separate game entry for each. We haven't yet finalized how to handle installation of multiple variants (which may have _some_ files common and possibly one-way dependency) and selection of one of the variants (its planned for next release), maybe we will have it display the list of installed variants (if more than one) to select when the user hits [Load Game] button and go from there.

Here <fileset> tag is supposed to have "name" and "id" attributes, and maybe "parent" (which is currently handled by "primary=[true|false]" attribute to the same effect, which does not handle multiple levels of hierarchy. Also we need something to convey reuse of certain files across variants for cases where only a few of the ROM files are supplied and rest are expected from the parent game's set. Of course, v1 will still work with prospective new games.xml format since all the new attributes will be ignored and filesets are handled differently.

Ideally all hacks of a game should work since they use the same hardware and share most of the code. Its probably configuration, but may as well be some deviation from the original.

Again, thanks for your help.

Girish

**Comment by FelixV** [comment]
my games  xml uses split sets, since i had some questions about the way the xml was set up.
of course then i figured out its basically set up the same way as a mame driver which makes things 
so much easier. of course then i looked at crush roller and saw that the xml shows
&lt;group name="maincpu" size="4000"&gt;
and mame shows
ROM_REGION( 0x10000, "maincpu", 0 )

will email you my games.xml as requested maybe you can see if i am missing something :)

**Comment by FelixV** [comment]
instead of using primary=true/false, why not just use 

primary=true

else

primary=name of parent

which should then read the parent xml tree in, 
then read the selected tree in, overwriting common branches/elements.
